export const stageIds = ['browser', 'app', 'database', 'balancer', 'cache', 'queue', 'worker', 'gateway'] as const;
export type StageId = typeof stageIds[number];
interface Stage {
  component: string; role: string; outcome: string; task: string; question: string;
  answers: { id: string; label: string }[]; correct: string; explanation: string; hint: string;
}
export const componentStages: Record<StageId, Stage> = {
  browser: { component: 'Web Browser', role: '入力して、返事を表示する', outcome: '利用者の操作が要求になり、返事が画面に表示される流れを追う', task: '道具の貸出状況を調べます。ボールについて尋ね、教材の応答先から受け取った返事を利用者の画面に表示してください。', question: 'ブラウザが担当したのは？', answers: [{ id: 'display', label: '利用者の入力を受け取り、返事を画面に表示する' }, { id: 'store', label: 'すべての利用者の記録を永続的に保存する' }], correct: 'display', explanation: 'ブラウザは利用者との窓口です。ボタンの操作を要求として送り、戻ってきた返事を画面に表示します。', hint: 'Web Browserから教材の応答先へつなぎ、ブラウザの「ボールの貸出状況を調べる」を押しましょう。返事は自動で画面に表示されます。' },
  app: { component: 'App Server', role: '要求を受けて処理する', outcome: 'ブラウザからアプリへ要求を届け、返事を返す', task: '道具の貸出サービスです。画面から処理担当までの経路を直し、返事を受け取ってください。', question: 'アプリをつないだことで、何ができましたか？', answers: [{ id: 'process', label: '届いたお願いを処理し、結果をブラウザへ返す' }, { id: 'backup', label: '保存先がなくても再起動後に記録を戻す' }], correct: 'process', explanation: '処理を担当するアプリまで要求が届く経路が必要です。永続的な保存は別に考えます。', hint: '線は要求の通り道です。ブラウザとアプリをつないでから送信してください。' },
  database: { component: 'RDBMS (SQL)', role: 'あとで使う記録を残す', outcome: 'アプリを再起動しても、DBから記録を読み出す', task: '「Aさんがボールを借りた」という記録を、アプリの再起動後にも読み出せるようにしてください。DBを追加し、アプリからつないでみましょう。', question: '今回、再起動後にも読めた理由は？', answers: [{ id: 'separate', label: 'アプリとは別のDBに記録を残したから' }, { id: 'all', label: 'DBを置けば誤削除やDB自身の故障も防げるから' }], correct: 'separate', explanation: '停止したのはアプリだけです。DBの故障や誤削除への備えまでできたわけではありません。', hint: '配置しただけでは保存できません。DBへの接続を確かめ、保存→再起動→読み出しを試します。' },
  balancer: { component: 'Load Balancer', role: '使える処理先へ振り分ける', outcome: '停止したアプリを避け、残る能力の範囲で処理する', task: 'アプリAは停止済み。1秒に6件の要求があります。使えるアプリへ振り分け、6件とも処理してください。', question: 'この構成で、まだ考える必要があるのは？', answers: [{ id: 'shared', label: '共通のDBや入口の故障、残ったアプリの能力' }, { id: 'none', label: '1台止まっても処理できたので、ほかの故障対策は不要' }], correct: 'shared', explanation: '振り分け先が残っても、処理能力は減ります。入口や共通DBが止まる場合も別に設計します。', hint: '停止中のAだけでは処理できません。2台にし、入口で稼働中のBへ振り分けましょう。' },
  cache: { component: 'Distributed Cache', role: 'よく使う情報のコピーを返す', outcome: '古いコピーを無効化し、最新の情報を取り直す', task: '会場は「公園」から「体育館」へ変更されました。図のキャッシュには以前のコピーがある想定です。接続して古い表示を確認し、キャッシュを使ったまま最新の会場を表示してください。', question: 'コピーを使う際に決めることは？', answers: [{ id: 'fresh', label: 'いつ無効化するか、どの程度の古さを許容するか' }, { id: 'forever', label: '一度作ったコピーを変更せず永久に使うこと' }], correct: 'fresh', explanation: '読み出しを減らせても、表示が古いままでは用途を満たさない場合があります。', hint: 'まず読んで古い表示を確かめます。コピーを無効化してから、もう一度読みましょう。' },
  queue: { component: 'Message Queue', role: 'あとで処理する仕事を預かる', outcome: 'Workerが止まっていても仕事を受け付け、完了と区別する', task: '通知担当のWorkerは停止中です。利用者に完了を待たせずに仕事を受け付け、通知待ちとして残してください。', question: '仕事を受け付けた今、利用者に伝えられるのは？', answers: [{ id: 'accepted', label: '受付済み。通知の完了はまだ確認できていない' }, { id: 'delivered', label: '通知は相手に届いた' }], correct: 'accepted', explanation: 'キューが保持しているのは未完了の仕事です。受付成功と処理完了を区別します。', hint: 'キューを使う状態で通知を依頼します。通知の実行数と待機中の仕事の数を見比べましょう。' },
  worker: { component: 'Worker (Async)', role: '預かった仕事を取り出して実行する', outcome: '再配信された同じ仕事を二重に実行しない', task: '同じ仕事 #1 が2件届いています。Workerを再開し、待機を空にしてください。通知は1回だけ実行する必要があります。', question: '同じ仕事が再配信されたときの備えは？', answers: [{ id: 'id', label: '仕事IDと処理済み記録を使い、重複を安全に扱う' }, { id: 'speed', label: 'Workerを速くすれば重複配信は必ずなくなる' }], correct: 'id', explanation: '処理を速くすることと重複を防ぐことは別です。教材では処理済みIDを確認して2回目を抑えます。', hint: '重複防止を有効にし、Workerを再開します。2件とも取り出し、実行回数が増えないことを確かめます。' },
  gateway: { component: 'API Gateway', role: '入口で受け付ける量を調整する', outcome: '見送られた要求を、時間を空けて再試行する', task: '7件の要求を送ります。アプリは1秒に3件まで。入口の利用制限を使い、見送り分を再試行して7件すべて処理してください。', question: '断られた要求をあとで処理できたのは？', answers: [{ id: 'retry', label: '利用者側で待ち、改めて要求を送ったから' }, { id: 'server', label: '利用制限が必ず仕事をサーバー内に保管するから' }], correct: 'retry', explanation: '教材のAPI Gatewayでは利用制限を学びました。見送り分は利用者側で再試行し、キューに保存されたとは扱いません。', hint: '制限を有効にして送信します。見送り分が0件になるまで、1秒進める→再試行を繰り返しましょう。' },
};
